baseURL = "https://molkaout.github.io/"
languageCode = "en-us"
title = "MoveLikeJaggy"
theme = "hugo-nuo"

[params]
  author = "MolkaOut"
  avatar = "/img/avatar.jpg"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"